import os
import pandas as pd
from tabulate import tabulate

def generate_data_quality_report():
    csv_path = os.path.join("data", "Sales.csv")
    report_path = os.path.join("reports", "Data_Quality_Report.md")
    img_null_chart = "../visuals/06_Order_Amount_Distribution.png"
    
    if not os.path.exists(csv_path):
        csv_path = "01-sales-analysis/data/Sales.csv"
        report_path = "01-sales-analysis/reports/Data_Quality_Report.md"
        img_null_chart = "visuals/06_Order_Amount_Distribution.png"

    df = pd.read_csv(csv_path)

    total_rows = len(df)
    total_cols = len(df.columns)
    duplicate_count = df.duplicated().sum()
    
    quality_data = []
    for col in df.columns:
        missing = df[col].isna().sum()
        missing_pct = (missing / total_rows) * 100
        data_type = str(df[col].dtype)
        unique_vals = df[col].nunique()
        
        status = "Pass" if missing == 0 else "Fix Needed"
        missing_str = f"{missing} ({missing_pct:.1f}%)"
        
        quality_data.append([col, data_type, missing_str, unique_vals, status])
        
    quality_headers = ["Attribute Name", "Storage Type", "Missing Records (Null %)", "Unique Entries", "Integrity Status"]
    matrix_table = tabulate(quality_data, headers=quality_headers, tablefmt="github")

    structure_data = [
        ["Total Data Rows", f"{total_rows} Records"],
        ["Total Columns Count", f"{total_cols} Columns"],
        ["Duplicate Rows Found", f"{duplicate_count} Matches"]
    ]
    structure_table = tabulate(structure_data, headers=["Structural Component", "Value Metrics"], tablefmt="github")

    findings_data1 = [
        ["Missing Prices", "Amount_INR contains missing structural lines (NaN / Null discovered).", "Implement fallback calculation using baseline quantity and price multipliers."],
        ["Missing Totals", "Final Amount contains uncalculated empty lines (NaN / Null discovered).", "Deploy patch script using price and discount formulas to backfill blank records."]
    ]
    findings_table1 = tabulate(findings_data1, headers=["Data Category", "Logged Finding", "Operational Action Item"], tablefmt="github")

    findings_data2 = [
        ["Record Overlap", f"Found {duplicate_count} duplicated transaction items.", "Deduplicate dataset profiles before triggering final financial pipelines."]
    ]
    findings_table2 = tabulate(findings_data2, headers=["Metrics Metric", "Scan Finding", "Operational Action Item"], tablefmt="github")

    steps_data = [
        ["**Step 1 - Structural Backfill**", "Blank records introduce aggregation skew.", "Fill missing numeric variables using formula rows or remove records safely."],
        ["**Step 2 - Format Alignment**", "Date sequences might drop string tags.", "Format all timeline stamps strictly into unified pandas timestamp matrices."],
        ["**Step 3 - Deduplication Drop**", "Duplicate items artificially inflates gross values.", "Run drop duplicates method across unique identifier combinations."]
    ]
    steps_table = tabulate(steps_data, headers=["Validation Phase", "Identified Risk Factor", "Mandatory Data Correction"], tablefmt="github")

    report_content = f"""# 📊 Data Quality Summary Report

**Project:** Sales Data Validation Pipeline
**Report Type:** Data Integrity Check
**Generated On:** *Automatically Generated by Python Script*

---

# 📌 Dataset Overview

This validation script runs basic structural and health checks over the primary source files to flag null records, format tracking errors, and duplicate entries.

The process guarantees data completeness before passing variables onto production metrics engines.

---

# ⚙️ Core Structure Profile

{structure_table}

---

# 🔍 Complete Attribute Quality Matrix

{matrix_table}

---

# 📊 Detailed Integrity Findings

## 1. Null Record Anomalies

{findings_table1}

### 📉 Missing Values & Data Skew Visualization
Below is the data distribution chart highlighting areas affected by missing ticket rows:

![Data Quality Integrity Chart]({img_null_chart})

---

## 2. Row Duplicate Check

{findings_table2}

---

# 💡 Strategic Quality Remediation Steps

{steps_table}

---

# 📁 Verification Meta Context

| Configuration Item | Environment Value |
| ------------------ | ----------------- |
| Source Document    | Sales.csv         |
| Engine Language    | Python Script     |
| Pipeline Library   | Pandas            |
| Profile Target     | Markdown (.md)    |

---

**End of Quality Report**"""

    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print(f"\n📄 [SUCCESS] Data Quality Report updated using Raw Sales.csv: {report_path}")

if __name__ == "__main__":
    generate_data_quality_report()
